export const KEPERLUAN_OPTIONS = [
  'Bantuan Beasiswa',
  'Persyaratan Administrasi Kependudukan',
  'Persyaratan Pengajuan Kredit Bank',
  'Pengajuan Bantuan Sosial (Bansos)',
  'Pengajuan KUR / Tambahan Modal Usaha',
  'Pengurusan SKCK / Kepolisian',
  'Pendaftaran Kerja / Lamaran Kerja',
  'Pengurusan Perizinan Usaha (NIB/SIUP/UMKM)',
  'Pengurusan BPJS Kesehatan / Ketenagakerjaan',
  'Penerimaan Bantuan Rumah Tidak Layak Huni (RTLH)',
  'Pengurusan Kartu Indonesia Pintar (KIP)',
  'Persyaratan Nikah',
  'Pengurusan Surat Tanah / Sertifikat',
  'Kepentingan Sekolah / Administrasi Pendidikan',
  'Pengurusan Kartu Keluarga (KK)',
  'Pengurusan KTP Elektronik',
  'Penggantian Dokumen yang Hilang',
  'Pengurusan Pensiun / Jaminan Sosial',
  'Persyaratan Melamar ke Instansi Pemerintah',
  'Keperluan Lainnya',
];